GET http://localhost:8000/products/2/ HTTP/1.1
Host: localhost:8000

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0OTgwMjgxLCJpYXQiOjE3NTQ5Nzk5ODIsImp0aSI6IjZlNGU0MjkwMjVlNzQ0MDM5N2I0OGNkNWNiZTQwMDkzIiwidXNlcl9pZCI6IjEifQ.1yqRZB--sTZ9Qir3btvnZx2enX8Cr5wyVfazu6kLdl8

{
    "name": "Updated Product",
    "price": 29.99,
    "stock": 150,
    "description": "An updated product description"
}

###
DELETE http://localhost:8000/products/2/ HTTP/1.1
Host: localhost:8000


### This File uses the VS Code extension REST Client

POST http://localhost:8000/products/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0OTc3MTA3LCJpYXQiOjE3NTQ5NzY4MDcsImp0aSI6ImVhYWNhNjZiODQ4NTQ3ZjdiMjY3YjRmY2MyMzg3MGVmIiwidXNlcl9pZCI6IjIifQ.HgrcfqDVhPgYcYh2B427w0JN4LYO9INRenZ8G_fuA4c

{
    "name": "New Product",
    "price": 19.99,
    "stock": 100,
    "description": "A brand new product"
}

### JWT Authentication
POST http://localhost:8000/api/token/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

### Gets a new access token using the refresh token

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTA2NTYxOCwiaWF0IjoxNzU0OTc5MjE4LCJqdGkiOiJiMGVlYzFmYmFkMzY0ZDRmYmJhMDZkMDFmNjEyOTljNyIsInVzZXJfaWQiOiIxIn0.k_RxWHD2EwC-bklpZnDrAhCJlATjONte5qCDQogLGKk"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0OTc5MDA5LCJpYXQiOjE3NTQ5Nzg3MDksImp0aSI6IjcyN2E5MTg1NjE0NTQ0ZmE5OTY3NzhhYzZiMzk1MzZmIiwidXNlcl9pZCI6IjEifQ.9VcShNYKgrGcsG_tyHxv52LBxJy_LB8QhSDWHbVndjQ

###
GET http://localhost:8000/orders/cd856841-d846-4034-bfb4-cbbd0f14905e/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDU3MTQ1LCJpYXQiOjE3NTUwNTY4NDUsImp0aSI6IjhjYTRiZmQ0NmI2MDQ3Nzc5NGU1M2ZkZjI1ZTc0ZWU5IiwidXNlcl9pZCI6IjIifQ.e9La8ei-wulRyIJ-rQpowDDP4b5d_5Ukm1-G3reK3m8

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDgwNzM2LCJpYXQiOjE3NTUwODA0MzYsImp0aSI6IjU3YThlOWNhNmZiODRlM2ViYjg2ZWExZjU0ZTRkOGRkIiwidXNlcl9pZCI6IjEifQ.Y75I_pu-2QV16BWRcEBTbCDxWSp4DRpxiqutmqLfqsM

{
	"status": "pending",
	"items": [
		{
				"product": 2,
				"quantity": 2
		},
		{
				"product": 3,
				"quantity": 1
		}
	]	
}